name: 'dbt_dataengineers_utils'
version: '1.0.0'
config-version: 2

require-dbt-version: [">=1.9.4", "<3.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
docs-paths: [docs]
