name: 'dbt_dataengineers_utils'
version: '0.2.4'
config-version: 2

require-dbt-version: [">=1.3.0", "<2.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
