name: 'dbt_dataengineers_utils'
version: '0.3.5.1'
config-version: 2

require-dbt-version: [">=1.7.0", "<2.0.0"]

target-path: "target"
clean-targets: ["target", "dbt_modules", "dbt_packages"]
macro-paths: ["macros"]
docs-paths: [docs]
