version: 2

macros:
  - name: enable_dependent_tasks
    description: This macro enables the task dependants of a task
    docs:
      show: true
    arguments:
      - name: root_task
        type: string
        description: the name of the task to enable the dependants of
      - name: enabled_targets
        type: List[string]
        description: List of environments/targets to enable in

  - name: execute_task
    description: This macro executes a task in the context of a target
    docs:
      show: true
    arguments:
      - name: task_name
        type: string
        description: the name of the task to execute
      - name: enabled_targets
        type: List[string]
        description: A list of environments or targets (e.g., "dev", "staging", "prod") where the task should be executed.
