version: 2

macros:
  - name: enable_dependent_tasks
    description: Enable all dependent (downstream) tasks for a given root task when target allowed.
    docs:
      show: true
    arguments:
      - name: root_task
        type: string
        description: the name of the task to enable the dependants of
      - name: enabled_targets
        type: List[string]
        description: List of environments/targets to enable in

  - name: execute_task
    description: Execute a task for the current target if the environment is enabled.
    docs:
      show: true
    arguments:
      - name: task_name
        type: string
        description: the name of the task to execute
      - name: enabled_targets
        type: List[string]
        description: A list of environments or targets (e.g., "dev", "staging", "prod") where the task should be executed.
