version: 2

macros:
  - name: database_clone
    description: Clone (zero-copy) a source database into a new destination database optionally transferring ownership.
    arguments:
      - name: source_database
        description: Source database name, i.e. database to be cloned
      - name: destination_database
        description: Destination database name, i.e. the new database to be created
      - name: new_owner_role
        description: "[Optional] The new owner role of the newly created object"

  - name: schema_clone
    description: Clone (zero-copy) a source schema into a destination schema; database defaults to target if not supplied.
    arguments:
      - name: source_schema
        description: Source schema name, i.e. schema to be cloned
      - name: destination_schema
        description: Destination schema name, i.e. the new schema to be created
      - name: source_database
        description: "[Optional] Source database name. Defaults to target database."
      - name: destination_database
        description: "[Optional] Destination database. Defaults to target database."
      - name: new_owner_role
        description: "[Optional] The new owner role of the newly created object"

  - name: database_destroy
    description: Drop the supplied database (destructive operation).
    arguments:
      - name: database_name
        description: Database to drop
